export const avatarList = [
  {
    id: "default",
    name: "잔챙이",
    imageUrl: "/avatars/default.png",
    unlockLevel: 1,
    conditionText: "기본 아바타입니다.",
  },
  {
    id: "girlfriend",
    name: "여자친구",
    imageUrl: "/avatars/girlfriend.png",
    unlockLevel: 5,
    conditionText: "레벨 5 이상",
  },
  {
    id: "lv10",
    name: "조직 부하",
    imageUrl: "/avatars/lv10.png",
    unlockLevel: 10,
    conditionText: "레벨 10 이상",
  },
  {
    id: "lv30",
    name: "조직 보스",
    imageUrl: "/avatars/lv30.png",
    unlockLevel: 30,
    conditionText: "레벨 30 이상",
  },
  {
    id: "gay",
    name: "태형GaY",
    imageUrl: "/avatars/gay.png",
    unlockLevel: 50,
    conditionText: "레벨 50 이상",
  },
  {
    id: "monster",
    name: "몬스터",
    imageUrl: "/avatars/monster.png",
    unlockLevel: 99,
    conditionText: "이벤트 보상",
  },
  {
    id: "killjennet",
    name: "킬제넷",
    imageUrl: "/avatars/killjennet.png",
    unlockLevel: 999,
    conditionText: "김태형 죽이기 1000점 이상",
  },
  {
    id: "enhance",
    name: "사이버펑크 태형",
    imageUrl: "/avatars/enhance.png",
    unlockLevel: 999,
    conditionText: "김태형 강화하기 최종강화 성공",
  },
  {
    id: "brick",
    name: "벽돌 태형",
    imageUrl: "/avatars/brick.png",
    unlockLevel: 999,
    conditionText: "김태형 벽돌깨기 1000점 이상",
  },
  {
    id: "special1",
    name: "우정",
    imageUrl: "/avatars/special1.png",
    unlockLevel: 9999,
    conditionText: "베타테스터 특전",
  },
  {
    id: "special2",
    name: "잘때 몰래..",
    imageUrl: "/avatars/special2.png",
    unlockLevel: 9999,
    conditionText: "베타테스터 특전",
  },
];
